#
#	Merchant Configuration
#
StoreID=T2G74
RSAName=keys/T2G74_PRIV.DER

#	Field default value
Deposit=0
QueryFlag=1
Currency=NTD
OrderDesc=default-desc
ReturnURL=http://localhost:8080/api/payment/return
UpdateURL=http://localhost:8080/api/payment/update

#	System pararmeter value